# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b967a967728fa11764973cfdee96f55b4c80a9b2f28bc90c3a94a56e2b2107bc94a04902fc95b63c92b85388dd84b036e2c2ebd8e0408000abf78f965f5279dd

test:
  secret_key_base: a2101bf5434f7aa16cdb548a512bce2c72c56cf4d6becaf734d9ade2c6a8d6cc2c455fc724b50cd1ac193007ff5cae81b7f8688764320ae714e458665b8092fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
